<?php
$title = $this->user->getLogin();
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<table class="table">
    <tr>
        <td>votes</td>
        <td><?= $this->user->getVotes() ?></td>
    </tr>
    <tr>
        <td>info</td>
        <td><?= $this->user->getInfo() ?></td>
    </tr>
    <tr>
        <td>avatar</td>
        <td><?= $this->user->getAvatar() ?></td>
    </tr>
</table>
