<?php

$date = date('j-m-Y G:i', strtotime($this->comment->getPostTime()));
$commenterLogin = $this->comment->getAuthor();
$verbStem = 'Написа';
switch ($this->commenterGender) {
    case Pepsite\Entity\User::GENDER_FEMALE:
        $verbEnding = 'ла';
        break;
    case Pepsite\Entity\User::GENDER_MALE:
    default:
        $verbEnding = 'л';
}
$verb = $verbStem . $verbEnding;
?>

<div class="card my-3">
    <div class="card-body">
        <?= $this->escapeHtml($this->comment->getContent()) ?>
    </div>
    <div class="card-text p-1 px-2 ml-auto">
        <small class="text-muted">
            <span class="mr-2"><?= $verb ?></span>
            <a class="font-weight-bold mr-2" href="<?= $this->url('user', ['login' => $commenterLogin]) ?>"><?= $commenterLogin ?></a>
            <span><?= $date ?></span>
        </small>
    </div>
</div>
