<?php
$login = $this->user->getLogin();
?>

<div class="user-row border rounded w-75 w-md-50 my-1 my-md-2">
    <div class="container-fluid p-0 mr-3">
        <a href="<?= $this->url('user', ['login' => $login]) ?>">
            <div class="d-inline-flex flex-row align-items-baseline">
                <div class="avatar border rounded p-0">
                    <img class="w-100" alt="(.__.)" src="<?= $this->avatar($this->user->getAvatar()) ?>"/>>
                </div>
                <div class="h4 p-0 m-0 ml-2"><?= $login ?></div>
            </div>
        </a>
        <div class="text-center display-4 user-score mt-2 p-0 pl-5">
            <?= $this->user->getVotes() ?>
        </div>
    </div>
    <div  class="d-flex flex-column justify-content-center align-items-center">
        <?= $this->partial('pepsite/partial/voteButtons.phtml', ['login' => $login, 'vote' => $this->vote]) ?>
    </div>
</div>