<?php
/** @noinspection PhpUndefinedMethodInspection */
$this->headTitle('Регистрация');

$login = $this->form->get('login');
$login->setAttribute('class', 'form-control');

$password = $this->form->get('password');
$password->setAttribute('id', 'password');
$password->setAttribute('class', 'form-control');

$avatar = $this->form->get('avatar');
$avatar->setAttribute('class', 'form-control-file');

$gender = $this->form->get('gender');
$gender->setAttribute('class', 'form-control');

$captcha = $this->form->get('captcha');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-lg btn-primary btn-block mt-4');

$messages = $this->form->getMessages();
$this->form->setAttribute('class', 'form-signin');
$this->form->prepare();
?>
<div class="text-center">
    <h1 class="h3 font-weight-normal">Регистрация</h1>
</div>

<?php if (!empty($messages)) : ?>
    <div class="container-fluid text-center">
        <div class="d-inline-flex flex-column align-items-start alert alert-danger">
            <?php
            foreach (array_values($messages) as $elementMessages):
                foreach (array_values($elementMessages) as $message) : ?>
                    <div class="d-inline-block py-1"><?= $message ?></div>
                <?php
                endforeach;
            endforeach;
            ?>
        </div>
    </div>
<?php endif; ?>

<?= $this->form()->openTag($this->form); ?>
    <div class="w-75 w-md-25 mx-auto">
        <div class="form-group my-2">
            <?= $this->formLabel($login) ?>
            <?= $this->formElement($login) ?>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($password) ?>
            <div class="d-flex flex-column align-items-start">
                <?= $this->formElement($password) ?>
                <div>
                    <input type="checkbox" id="showPass" onclick="togglePass()">
                    <label for="showPass">Показать пароль</label>
                </div>
            </div>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($avatar) ?>
            <?= $this->formFile($avatar) ?>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($gender) ?>
            <?= $this->formSelect($gender) ?>
        </div>
    </div>

    <div class="text-center form-group my-4 mx-auto">
        <?= $this->formCaptcha($captcha) ?>
    </div>

    <div class="w-75 w-md-25 mx-auto">
        <?= $this->formSubmit($submit); ?>
    </div>
<?= $this->form()->closeTag(); ?>
</div>

<script>
    function togglePass() {
        let pass = document.getElementById('password');
        if (pass.type === 'password') {
            pass.type = 'text';
        } else {
            pass.type = 'password';
        }
    }
</script>
