<?php
/** @noinspection PhpUndefinedMethodInspection */
$this->headTitle('Регистрация');

$login = $this->form->get('login');
$login->setAttribute('class', 'form-control');

$password = $this->form->get('password');
$password->setAttribute('class', 'form-control');

$avatar = $this->form->get('avatar');
$avatar->setAttribute('class', 'form-control');

$gender = $this->form->get('gender');
$gender->setAttribute('class', 'form-control');

$captcha = $this->form->get('captcha');

$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-lg btn-primary btn-block mt-4');

$this->form->setAttribute('class', 'form-signin');
$this->form->prepare();
?>
<div class="d-flex flex-column align-items-center">
    <?= $this->form()->openTag($this->form); ?>
        <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
        <div class="form-group">
            <?php
            foreach ($this->form as $element) {
                echo $this->formElementErrors($element, ['class' => 'help-block']);
//                echo var_dump($element);
            }
            ?>
        </div>
        <div class="form-group my-2">
            <?= $this->formLabel($login) ?>
            <?= $this->formElement($login) ?>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($password) ?>
            <div class="d-flex justify-content-between align-items-center">
                <div class="w-75">
                    <?= $this->formElement($password) ?>
                </div>
                <div>
                    <input type="checkbox" id="showPass" onclick="togglePass()">
                    <label for="showPass">Показать пароль</label>
                </div>
            </div>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($avatar) ?>
            <?= $this->formFile($avatar) ?>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($gender) ?>
            <?= $this->formSelect($gender) ?>
        </div>

        <div class="form-group mb-2">
            <?= $this->formLabel($captcha) ?>
            <?= $this->formCaptcha($captcha) ?>
        </div>
        <?= $this->formSubmit($submit); ?>
    <?= $this->form()->closeTag(); ?>
</div>

<script>
    function togglePass() {
        let pass = document.getElementById('password');
        if (pass.type === 'password') {
            pass.type = 'text';
        } else {
            pass.type = 'password';
        }
    }
</script>
