<div class="navbar text-right mb-3 p-0">
    <div class="mr-auto px-0">
        <p>Pepyaka site 0.7</p>
    </div>
    <?php if (is_null($this->identity)) : ?>
        <div class="mx-2">
            <a href="<?= $this->url('register') ?>">Зарегистрироваться</a>
        </div>
        <div class="mx-2">
            <a href="<?= $this->url('login') ?>">Войти</a>
        </div>
    <?php else: ?>
        <div class="d-flex justify-content-between align-items-center w-25">
            <p><?= $this->identity->getLogin() ?></p>
            <p><?= $this->identity->getVotes() ?></p>
            <a href="<?= $this->url('logout') ?>">Выйти</a>
        </div>
    <?php endif; ?>
</div>