<?php if (!is_null($this->user)) : ?>
<h1>Wellcome, <?= $this->user->getLogin() ?></h1>
<?php endif; ?>
<table class="table">
    <?php foreach ($this->topUsers as $user) : ?>
    <tr>
        <td>
            <a href="<?= $this->url('user', ['login' => $user->getLogin()]) ?>">
                <h2><?= $user->getLogin() ?></h2>
            </a>
        </td>
    <?php endforeach; ?>
    </tr>
</table>
