<?= $this->mainNav()->render() ?>
<div class="d-flex flex-column w-25">
    <ul class="list-unstyled">
    <?php foreach ($this->topUsers as $topUser) : ?>
        <li>
            <div class="d-flex justify-content-between">
                <a href="<?= $this->url('user', ['login' => $topUser->getLogin()]) ?>"><p><?= $topUser->getLogin() ?></p></a>
                <p><?= $topUser->getVotes() ?></p>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>